### ISSUE TITLE
Allow override text wrapping style inside api response

### ISSUE THREAD

**Issue by smujaddid** [rapi-doc/RapiDoc#1054]
![image](https://github.com/user-attachments/assets/725b35df-6791-4d07-ad5d-bd2841c1b003)

By editing in browser with these:
```css
.m-markdown-small pre code, .m-markdown pre code {
    border: none;
    padding: 0;
    text-wrap-mode: wrap;
    overflow-wrap: anywhere;
}
```

Will result what I want:
![image](https://github.com/user-attachments/assets/81c16eb5-1e9a-4738-aa33-a0e8ee089030)

But I can't find the way to override the style.
Please allow us to override code wrapping for api response.
