### ISSUE TITLE
Dynamic query params: issues with object parameters

### ISSUE THREAD

**Issue by mzsrn** [rapi-doc/RapiDoc#399]
Hi! 
I'm using this example - https://rapidocweb.com/examples/dynamic-query-params.html.

I've cleared all the params except `dynamic-query-params1`.
When i'm trying to send request those params look like this:
```
{
  "d":{ "d1":1, "d2":2 },
  "e":3
}
```
Output curl looks as follows:
```
curl -X GET "https://mrin9.github.io/dynamic-query-params?e=3?e=3?e=3" 
```

**Comment by mrin9** [comment]
well I am getting a `curl` output as `curl -X GET "https://mrin9.github.io/dynamic-query-params?e=3"`
which IMO seems correct.

can you tell me what is your expected behavior ?

**Comment by mzsrn** [comment]
i was hoping to see something like that
```
curl -X GET "https://mrin9.github.io/dynamic-query-params?d%5Bd1%5D=1&d%5Bd2%5D=2&e=3
```

**Comment by mrin9** [comment]
i c, you are correct, the output you specified is correct. however RapiDoc do not support `deepObject` in query parameters yet.

will use this issue to track this feature. Thanks for reporting

**Comment by OCharnyshevich** [comment]
I hope you will find time to implement this thing.

**Comment by hrvoj3e** [comment]
Is this on the roadmap soon?
This would be most useful on my current project.

```yaml
    - in: query
      name: filterfc
      style: deepObject
      explode: true
      schema:
        type: object
        additionalProperties: {}
      example: >
        {
          "facetA": {"valueA": "a"},
          "facetB": "value"
        }
```
