### ISSUE TITLE
Query String which is an object is rendered as [object Object] instead of the actual object

### ISSUE THREAD

**Issue by ThaDaVos** [rapi-doc/RapiDoc#800]
In query strings one can use query parameters as follows; `param[a][b][c]=1` - to do this inside OpenAPI one defines the query parameter to be an object, the schema is rendered correctly but sadly the example is not as seen below:

Schema:
![image](https://user-images.githubusercontent.com/5251028/184370099-2af4af5b-1919-43b4-b99b-e70bc876b877.png)
Example:
![image](https://user-images.githubusercontent.com/5251028/184370145-08dc4391-3a74-4020-ab39-e3303bebed0a.png)

This makes testing really cumbersome as one has to manually type it out

**Comment by mrin9** [comment]
can you provide an minimal sample spec for us to recreate this at our end for a quicker response

**Comment by rahpuser** [comment]
I think this basically happens when example is an object and not an string:

```
              examples:
                ok-response:
                  value:
                    message: Success
                    code: 200
```

This happen for all example types ( parameters, responses, etc )

This is rendered as `[object Object]`, as an alternative, we can pass it as a json serialized string, but in that scenario it kind of break that schema says is an object.
