### ISSUE TITLE
option to hide example value

### ISSUE THREAD

**Issue by hrvoj3e** [rapi-doc/RapiDoc#810]
Is it possible to hide example value?
If not, could you please add this option (globally and per param)?
(I added an example: `x-example-show-value: false`)

Before I used `use-summary-to-list-example="true"` but it is not available anymore. Or it is?

```yaml
in: header
name: token
schema:
  type: string
examples:
  a:
    summary: example-token
    description: my token example
    x-example-show-value: false
    value: |
      eyJhbGciOisfdxMiJ9.v9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2hv9ex4lvf3c7nryzxp7jz5y3jxhxk2h.fPqBlnJyL38U61u0ti0RhzLGRWRNIbNYjuFlSdJQJVkCT1zIaHY_4KWvvFCJMgXFf13BHV3SEjZXo9IKFHqiJg
```

![image](https://user-images.githubusercontent.com/4988133/187655387-7eb6ab5e-fdb1-4173-a295-69fdbc8237db.png)

This worked better before. I upgraded to 9.3.3 and values started showing by default. I think it is linked with this pull request https://github.com/rapi-doc/RapiDoc/pull/759 .

Another example would be when the value is so small (bool: 0, 1) it is hard to clock on it.

![image](https://user-images.githubusercontent.com/4988133/187836902-0792769a-e484-48c3-a6b1-f65c0ad09a67.png)
