### ISSUE TITLE
Request example doc delete starting zeros

### ISSUE THREAD

**Issue by alizaga** [rapi-doc/RapiDoc#828]
I have a request example string with starting zeros.

How can i disallow rapidoc to delete them?

Thanks

spec:
```
  'operation':
    get:
      ...
      parameters:
          ...
          schema:
            type: string
            format: ^.*$
          example: 00080161072
```
render:
![image](https://user-images.githubusercontent.com/93119407/192205179-620054d5-5027-4c46-b248-0b0fc0e2a18a.png)

**Comment by mrin9** [comment]
this is a `yaml` parsing issue as our yaml parser will auto convert this value to number. To avoid it use quotes to use it as string

```yml
  'operation':
    get:
      ...
      parameters:
          ...
          schema:
            type: string
            format: ^.*$
          example: "00080161072" # <-- enclose in quotes
```
