### ISSUE TITLE
anyOf/oneOf incorrectly assume type: object

### ISSUE THREAD

**Issue by MartinKolarik** [rapi-doc/RapiDoc#922]
```yaml
resolvers:
  type: array
  items:
    oneOf:
      - type: string
        format: ipv4
      - type: string
        const: private

```

Renders incorrectly as an array of objects instead of an array of strings:

![image](https://user-images.githubusercontent.com/6192491/235509393-8f477595-f828-45a4-8486-342519438d0b.png)

Similarly, a more basic example without using `format`:

```yaml
resolvers:
  type: array
  description: A list of default DNS resolvers configured on the probe.
  items:
    oneOf:
      - type: string
      - type: integer
```

Should be an array of `string | integer` but is an array of objects:

![image](https://user-images.githubusercontent.com/6192491/235509780-8d8fdfd9-2600-4244-adc2-bab54dbd5576.png)

![image](https://user-images.githubusercontent.com/6192491/235509884-571d35a9-36c4-413e-ab47-57e11681318f.png)
