### ISSUE TITLE
Params serialization json not supported?

### ISSUE THREAD

**Issue by nop1984** [rapi-doc/RapiDoc#924]
```
    ServiceLevelAgreement_Fields:
      in: query
      name: fields
      description: By default, only the "name" field is included in the listing, to
        add more fields, you can pass the fields param to GET request. For example,
        fields=["name","country"]
      content:
        application/json:
          schema:
            default: '["name"]'
            type: array
            items:
              type: string
              enum:
              - enable
              - service_level
              - default_priority
              - default_service_level_agreement
              - employee_group
              - holiday_list
              - entity_type
              - entity
              - condition
              - condition_description
              - start_date
              - active
              - end_date
              - pause_sla_on
              - priorities
              - support_and_resolution
```

This is expected to be encoded as `?fields=["enable", "service_level"]` and SweagerUI does that, but rapidoc keeps it `?fields=enable,service_level`
