### ISSUE TITLE
SCHEMA -> Multiline description is broken (height)

### ISSUE THREAD

**Issue by serhii-bilyk-intellias** [rapi-doc/RapiDoc#981]
Hi, `SCHEMA -> Multiline description` seems broken:
![image](https://github.com/rapi-doc/RapiDoc/assets/144336942/e8ab25ee-eb79-487f-b2ba-e2725f8c1143)

Was trying to fix CSS for `.tr.expanded.object` but this selection is not appliable:
```css
rapi-doc::part(schema-description) + div.tr.expanded.object {
    display: block
  }
```
I can set CSS only for elements with `part` attribute
